[versions]
agp = "7.2.0"
androidx-test = "1.4.0"
kotlin = "1.6.21"

[plugins]
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.19.0" }
binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.9.0" }

[libraries]
androidx-annotation = "androidx.annotation:annotation:1.3.0"
androidx-test-orchestrator = "androidx.test:orchestrator:1.4.1"
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-truth = "androidx.test.ext:junit:1.1.3"
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
desugarJdkLibs = "com.android.tools:desugar_jdk_libs:1.1.5"
javapoet = "com.squareup:javapoet:1.13.0"
junit = "junit:junit:4.13.2"
kgp = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kgp-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
kotlinpoet = "com.squareup:kotlinpoet:1.11.0"
okio = "com.squareup.okio:okio:3.1.0"
truth = "com.google.truth:truth:1.1.3"
zipflinger = { module = "com.android:zipflinger", version.ref = "agp" }